export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <ul>
            <li>HOME</li>
          </ul>
        </header>
        { children }
      </body>
    </html>
  )
}
